# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

# RxSwift, Swift Lint
target 'Pupago' do
    pod 'RxSwift', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'
    pod 'Alamofire', '~> 5.2'
    pod 'RxDataSources', '~> 4.0'
    pod "SwiftLint"
    pod 'Socket.IO-Client-Swift', '~> 15.2.0'
    pod 'Kingfisher'
    pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'
end

# RxTest
target 'PupagoTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5.0'
    pod 'RxTest', '~> 5.0'
end
